mybatis:
  type-aliases-package: com.bdqn.entity
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appinfodb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 8080
  address: 127.0.0.1